### ISSUE TITLE
No need for global Name constraint on speaker names in approval process

### ISSUE THREAD

**Issue by ahf** [bornhack/bornhack-website#1145]
Right now we cannot have multiple speakers with the same name. We should allow this as speakers can submit multiple events where they want multiple profiles.

For 2022, we had to modify the 3 `halfd` objects to be `halfd`, `halfd-1`, and `halfd-2`. We can continue having a constraint such that a single event cannot have multiple speakers with the same name, but globally it should be fine to have multiple events with the same name.

**Comment by 0xUnicorn** [comment]
This is the returned error:
`ValidationError at /bornhack-2023/backoffice/proposals/speakers/89e8b889-88e6-4e17-bf8a-f95b2714b952/approve_reject/
{'__all__': ['Speaker with this Camp and Name already exists.']}`

When removing the `{"camp", "name"}` unique combo, following error gets returned:
`IntegrityError at /bornhack-2023/backoffice/proposals/speakers/89e8b889-88e6-4e17-bf8a-f95b2714b952/approve_reject/
duplicate key value violates unique constraint "program_speaker_camp_id_name_5c8ef3de_uniq"
DETAIL:  Key (camp_id, name)=(975d258e-0590-409d-9ecf-9868da995595, Test) already exists.`

The slug that causes this issue is at `program.models.py` line 1601 in the `save` method.
