### ISSUE TITLE
Handle negative stock

### ISSUE THREAD

**Issue by valberg** [bornhack/bornhack-website#263]
Somehow we have managed to get into a situation where we have -1 in fridge drawers.

This likely has to do with bank transfers being asynchronous and the stock code not taking into account that there are orders which are closed=True, paid=False, cancelled=False, meaning that they are probably awaiting action from the orga team.

How to handle this I'm unsure of.

**Comment by flummer** [comment]
I suggest changing the calculation in `left_in_stock` so that is looks at `cancelled = False`, instead of `paid = True`. This will have the effect that limited supply is reserved immediately, and then if an order is not paid within the time that orga decides, they will choose to cancel the order, and then the reservation is lost. At this time, the order could also be changed (individual lines) if more relevant.

It's also possible to change the quantity up if the order is still open, currently without a check. The `OrderDetailView` should probably have a check added to check for availability of additional items. and alert/prevent if sold out.

Similarly, it's also possible to order more than what is in stock. A check in `ProductDetailView` should probably alert the user that only so and so many items are available, maybe automatically adjust the quantity down.
