### ISSUE TITLE
Add overview of shifts of a user

### ISSUE THREAD

**Issue by zeltophil** [bornhack/bornhack-website#265]
When a user is in more than one team there currently isn't a way to see all shifts the user has signed up for side by side. It would be good to have an overview of all assigned shifts under the user account page or under the teams page. Maybe this could even be on the schedule page so it is possible to see the assigned shifts next to the events.

Thinking this one step further it would be nice to get a warning when a user tries to sign up for a shift that overlaps with another shift the user is already signed up for. The possibility to export shifts in some calender format or to enable reminder mails would also be helpful.

**Comment by valberg** [comment]
Fixed in https://github.com/bornhack/bornhack-website/commit/da639ff4cd76d33f76b9e7ad0a17d8b796020f80

You can see you shifts on https://bornhack.dk/bornhack-2018/teams/shifts and when trying to self-assign a shift which overlaps an already existing shift will show an error message.

@zeltophil what do you think?

**Comment by zeltophil** [comment]
@valberg Great! There is a typo now in "Team memberships neesdf be approved by a team responsible".

**Comment by valberg** [comment]
@zeltophil Hah perfect! Fixed :smile: I'll close this issue.
